# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: CI-CD

on:
  push:
#    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["1.5.4"]
    name: Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts

      - name: Cache dependencies
        run: deno cache deps.ts

      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t yaroslava .

      - name: Tag the Docker image
        run: docker tag yaroslava nlesommer/yaroslava:latest

      - name: Push the Docker image to the registry
        run: docker push nlesommer/yaroslava:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker rm yaroslava-container --force
            docker run -d --name yaroslava-container -e DISCORD_BOT_TOKEN="${{ secrets.DISCORD_BOT_TOKEN }}" nlesommer/yaroslava:latest
          
